### ISSUE TITLE
 iotccsdk - ERROR - ipcprovider - on_error:340 - Camera Restarted! Exiting!!

### ISSUE THREAD

**Issue by georgegoglodze** [microsoft/vision-ai-developer-kit#315]
Hello everyone, as soon as Camera starts I see the following log in "AIVisionDevKitGetStartedModule" module:      `iotccsdk - ERROR - ipcprovider - on_error:340 - Camera Restarted! Exiting!!`
Can you please advise what is the fix? I have reseted device and reprovisioned firmware as well.

**Comment by v-prsasa** [comment]
@georgegoglodze Hi George, We will look into this.

**Comment by v-prsasa** [comment]
@georgegoglodze George can you do full factory reset to the device and you should have latest firmware too. Below is the link to do full factory reset:
 https://azure.github.io/Vision-AI-DevKit-Pages/docs/reset/

**Comment by georgegoglodze** [comment]
Thanks for the reply @v-prsasa I did it exactly already but did it again as you asked but still no luck.
Error log:
![image](https://user-images.githubusercontent.com/52762176/83818042-4fa7f780-a694-11ea-99c6-0662fcea093f.png)

Firmware is the latest as well:
```
/home/admin # cat /etc/version
v0.5370_Perf
```

**Comment by v-prsasa** [comment]
@georgegoglodze Thanks for the update. Let me try once and will get back to you soon.

**Comment by georgegoglodze** [comment]
Thanks a lot. This is the URI I use on IoTEdge to pull ML Module:
  `    "ModelZipUrl": "https://irisprodeu2training.blob.core.windows.net/m-2490ebbfd819468db633f1c2e4012925/4637be70b2bd4183a5f3a6d109392e74.VAIDK.zip?sv=2017-04-17&sr=b&sig=k%2FML2E%2F8iCaxHGjgc1mkYZxwf5AIXWZedS%2Fc4WBPtT0%3D&se=2020-06-05T21%3A22%3A59Z&sp=r",
`

**Comment by georgegoglodze** [comment]
Hi @v-prsasa, by default the OS **date** was not correct I adjusted manually and so far works like a charm :) Thanks for the responses.
`date -s "4 Jun 2020 20:29:00"`

**Comment by v-prsasa** [comment]
@georgegoglodze Okay no problem. I am closing this issue.
Kindly reopen the case if further support is required

**Comment by v-prsasa** [comment]
Closing as issue is resolved now

**Comment by georgegoglodze** [comment]
Hi @v-prsasa  unfortunately the issue is still here...
I keep receiving the following error:

```
Confirmation of 204 received for {"ObjectsOfInterest": "[\"All\"]"}.
send: b'\x89\x80w\x870\xd9'
2020-06-06 03:08:39,514 - iotccsdk - ERROR - ipcprovider - on_error:340 - Camera Restarted! Exiting!!

```

I rebooted AI Camera couple times, restarted modules but no luck...

**Comment by v-prsasa** [comment]
Can you re-open this issue?

**Comment by georgegoglodze** [comment]
@v-prsasa  I dont know how I can reopen this issue... Please reopen if you can or point me to right steps so I can reopen on my own. thanks in advance.

**Comment by v-prsasa** [comment]
As per user request

**Comment by v-prsasa** [comment]
@georgegoglodze Have you checked with OS date?

**Comment by georgegoglodze** [comment]
@v-prsasa Yes, time/timezone is correct...

**Comment by v-prsasa** [comment]
@georgegoglodze Is your issue resolved?

**Comment by MS-Nikunja** [comment]
Hi @georgegoglodze Is your issue resolved?

**Comment by georgegoglodze** [comment]
Hello, no the issue is still open however we decided not to use the
camera going forward.
Please close the issue.

**Comment by v-prsasa** [comment]
Closing this case as per users confirmation
